from app.models.articolo import Articolo
from app.models.cliente import Cliente
from app.models.ordine import Ordine
from app.models.riga_ordine import RigaOrdine
from app.models.commessa import Commessa
from app.models.policy_cliente import PolicyCliente
from app.models.evento import Evento
from app.models.macchina import Macchina
from app.models.sync_log import SyncLog
from app.models.consegna_magazzino import ConsegnaMagazzino
from app.models.spedizione import Spedizione
from app.models.utente import Utente
