"""computed_v03_complete

Revision ID: efa004ca9777
Revises: 0b6da3445212
Create Date: 2026-03-25 13:55:51.007485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa004ca9777'
down_revision: Union[str, Sequence[str], None] = '0b6da3445212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computed_article_demand',
    sa.Column('computed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=False),
    sa.Column('total_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_open_demand', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('net_available_raw', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('computed_id')
    )
    op.create_index(op.f('ix_computed_article_demand_article_source_id'), 'computed_article_demand', ['article_source_id'], unique=True)
    op.add_column('computed_order_lines', sa.Column('is_open_line', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computed_order_lines', 'is_open_line')
    op.drop_index(op.f('ix_computed_article_demand_article_source_id'), table_name='computed_article_demand')
    op.drop_table('computed_article_demand')
    # ### end Alembic commands ###
