"""sync_tables_v01

Revision ID: 1f36c16421b0
Revises: 
Create Date: 2026-03-25 10:22:03.303670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f36c16421b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_articles',
    sa.Column('source_id', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('description_2', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=3), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('material_code', sa.String(length=25), nullable=True),
    sa.Column('category', sa.String(length=6), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('sync_change_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_customers',
    sa.Column('source_id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=110), nullable=True),
    sa.Column('address', sa.String(length=55), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=7), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('vat_number', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('sync_destinations',
    sa.Column('source_id', sa.String(length=6), nullable=False),
    sa.Column('customer_source_id', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('address', sa.String(length=55), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('sync_order_headers',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('order_number', sa.String(length=10), nullable=True),
    sa.Column('customer_source_id', sa.String(length=6), nullable=True),
    sa.Column('destination_source_id', sa.String(length=6), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('customer_order_ref', sa.String(length=20), nullable=True),
    sa.Column('delivery_method', sa.String(length=6), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('sync_order_lines',
    sa.Column('order_source_id', sa.BigInteger(), nullable=False),
    sa.Column('line_number', sa.BigInteger(), nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('article_description', sa.String(length=500), nullable=True),
    sa.Column('qty_ordered', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('qty_shipped', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('qty_packed', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('customer_line_ref', sa.String(length=15), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('order_source_id', 'line_number')
    )
    op.create_table('sync_productions',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('customer_source_id', sa.String(length=6), nullable=True),
    sa.Column('production_order', sa.String(length=10), nullable=True),
    sa.Column('qty_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('qty_to_produce', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('qty_produced', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('qty_in_progress', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('order_number', sa.String(length=10), nullable=True),
    sa.Column('order_line', sa.BigInteger(), nullable=True),
    sa.Column('planned_date', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('sync_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('records_read', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_deleted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_stock_movements',
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('depot_code', sa.String(length=6), nullable=True),
    sa.Column('qty_in', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('qty_out', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('movement_type', sa.String(length=1), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=True),
    sa.Column('document_number', sa.String(length=30), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_stock_movements')
    op.drop_table('sync_run')
    op.drop_table('sync_productions')
    op.drop_table('sync_order_lines')
    op.drop_table('sync_order_headers')
    op.drop_table('sync_destinations')
    op.drop_table('sync_customers')
    op.drop_table('sync_change_item')
    op.drop_table('sync_articles')
    # ### end Alembic commands ###
