"""fact_tables_v02

Revision ID: 33cf6e383cfa
Revises: 1f36c16421b0
Create Date: 2026-03-25 11:47:22.700392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cf6e383cfa'
down_revision: Union[str, Sequence[str], None] = '1f36c16421b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_articles',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=25), nullable=False),
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('description_2', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=3), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('material_code', sa.String(length=25), nullable=True),
    sa.Column('category', sa.String(length=6), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_fact_articles_source_id'), 'fact_articles', ['source_id'], unique=False)
    op.create_table('fact_customers',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=6), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=110), nullable=True),
    sa.Column('address', sa.String(length=55), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=7), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('vat_number', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_fact_customers_source_id'), 'fact_customers', ['source_id'], unique=False)
    op.create_table('fact_destinations',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=6), nullable=True),
    sa.Column('customer_source_id', sa.String(length=6), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('address', sa.String(length=55), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_derived_from_customer', sa.Boolean(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_fact_destinations_customer_source_id'), 'fact_destinations', ['customer_source_id'], unique=False)
    op.create_index(op.f('ix_fact_destinations_source_id'), 'fact_destinations', ['source_id'], unique=False)
    op.create_table('fact_order_lines',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_source_id', sa.BigInteger(), nullable=False),
    sa.Column('line_number', sa.BigInteger(), nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('article_description', sa.String(length=500), nullable=True),
    sa.Column('qty_ordered', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('qty_shipped', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('qty_packed', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('customer_line_ref', sa.String(length=15), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('order_source_id', 'line_number', name='uq_fact_order_lines_key')
    )
    op.create_index(op.f('ix_fact_order_lines_article_source_id'), 'fact_order_lines', ['article_source_id'], unique=False)
    op.create_index(op.f('ix_fact_order_lines_order_source_id'), 'fact_order_lines', ['order_source_id'], unique=False)
    op.create_table('fact_orders',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('order_number', sa.String(length=10), nullable=True),
    sa.Column('customer_source_id', sa.String(length=6), nullable=True),
    sa.Column('destination_source_id', sa.String(length=6), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('customer_order_ref', sa.String(length=20), nullable=True),
    sa.Column('delivery_method', sa.String(length=6), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_fact_orders_customer_source_id'), 'fact_orders', ['customer_source_id'], unique=False)
    op.create_index(op.f('ix_fact_orders_source_id'), 'fact_orders', ['source_id'], unique=False)
    op.create_table('fact_productions',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('production_order', sa.String(length=10), nullable=True),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('customer_source_id', sa.String(length=6), nullable=True),
    sa.Column('qty_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('qty_to_produce', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('qty_produced', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('qty_in_progress', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('order_number', sa.String(length=10), nullable=True),
    sa.Column('order_line', sa.BigInteger(), nullable=True),
    sa.Column('planned_date', sa.DateTime(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_fact_productions_article_source_id'), 'fact_productions', ['article_source_id'], unique=False)
    op.create_index(op.f('ix_fact_productions_customer_source_id'), 'fact_productions', ['customer_source_id'], unique=False)
    op.create_index(op.f('ix_fact_productions_source_id'), 'fact_productions', ['source_id'], unique=False)
    op.create_table('fact_stock_movements',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('depot_code', sa.String(length=6), nullable=True),
    sa.Column('qty_in', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('qty_out', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('movement_type', sa.String(length=1), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=True),
    sa.Column('document_number', sa.String(length=30), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_fact_stock_movements_article_source_id'), 'fact_stock_movements', ['article_source_id'], unique=False)
    op.create_index(op.f('ix_fact_stock_movements_source_id'), 'fact_stock_movements', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_stock_movements_source_id'), table_name='fact_stock_movements')
    op.drop_index(op.f('ix_fact_stock_movements_article_source_id'), table_name='fact_stock_movements')
    op.drop_table('fact_stock_movements')
    op.drop_index(op.f('ix_fact_productions_source_id'), table_name='fact_productions')
    op.drop_index(op.f('ix_fact_productions_customer_source_id'), table_name='fact_productions')
    op.drop_index(op.f('ix_fact_productions_article_source_id'), table_name='fact_productions')
    op.drop_table('fact_productions')
    op.drop_index(op.f('ix_fact_orders_source_id'), table_name='fact_orders')
    op.drop_index(op.f('ix_fact_orders_customer_source_id'), table_name='fact_orders')
    op.drop_table('fact_orders')
    op.drop_index(op.f('ix_fact_order_lines_order_source_id'), table_name='fact_order_lines')
    op.drop_index(op.f('ix_fact_order_lines_article_source_id'), table_name='fact_order_lines')
    op.drop_table('fact_order_lines')
    op.drop_index(op.f('ix_fact_destinations_source_id'), table_name='fact_destinations')
    op.drop_index(op.f('ix_fact_destinations_customer_source_id'), table_name='fact_destinations')
    op.drop_table('fact_destinations')
    op.drop_index(op.f('ix_fact_customers_source_id'), table_name='fact_customers')
    op.drop_table('fact_customers')
    op.drop_index(op.f('ix_fact_articles_source_id'), table_name='fact_articles')
    op.drop_table('fact_articles')
    # ### end Alembic commands ###
