"""core_run_v04

Revision ID: cc3d86f0809b
Revises: d8a9d6cb7458
Create Date: 2026-03-25 14:29:32.240314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3d86f0809b'
down_revision: Union[str, Sequence[str], None] = 'd8a9d6cb7458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rebuild_type', sa.String(length=20), nullable=False),
    sa.Column('sync_run_id_from', sa.BigInteger(), nullable=True),
    sa.Column('sync_run_id_to', sa.BigInteger(), nullable=True),
    sa.Column('aggregates_rebuilt', sa.Integer(), nullable=True),
    sa.Column('records_rebuilt', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_run')
    # ### end Alembic commands ###
