"""fact_destinations_name_varchar110

Revision ID: 0dda4c50ba5c
Revises: 33cf6e383cfa
Create Date: 2026-03-25 12:03:02.530718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dda4c50ba5c'
down_revision: Union[str, Sequence[str], None] = '33cf6e383cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_destinations', 'name',
               existing_type=sa.VARCHAR(length=55),
               type_=sa.String(length=110),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_destinations', 'name',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=55),
               existing_nullable=True)
    # ### end Alembic commands ###
