"""computed_tables_v03

Revision ID: 0b6da3445212
Revises: 0dda4c50ba5c
Create Date: 2026-03-25 13:37:29.244763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6da3445212'
down_revision: Union[str, Sequence[str], None] = '0dda4c50ba5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computed_order_lines',
    sa.Column('computed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_source_id', sa.BigInteger(), nullable=False),
    sa.Column('line_number', sa.BigInteger(), nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('qty_ordered', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('qty_shipped', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('qty_remaining', sa.Numeric(precision=13, scale=5), nullable=True),
    sa.Column('is_fully_shipped', sa.Boolean(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('computed_id'),
    sa.UniqueConstraint('order_source_id', 'line_number', name='uq_computed_order_lines_key')
    )
    op.create_index(op.f('ix_computed_order_lines_article_source_id'), 'computed_order_lines', ['article_source_id'], unique=False)
    op.create_index(op.f('ix_computed_order_lines_order_source_id'), 'computed_order_lines', ['order_source_id'], unique=False)
    op.create_table('computed_production_status',
    sa.Column('computed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=False),
    sa.Column('qty_in_production', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('open_order_count', sa.BigInteger(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('computed_id')
    )
    op.create_index(op.f('ix_computed_production_status_article_source_id'), 'computed_production_status', ['article_source_id'], unique=True)
    op.create_table('computed_stock_balances',
    sa.Column('computed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_source_id', sa.String(length=25), nullable=True),
    sa.Column('depot_code', sa.String(length=6), nullable=True),
    sa.Column('qty_in_total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('qty_out_total', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stock_balance', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('movement_count', sa.BigInteger(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('computed_id'),
    sa.UniqueConstraint('article_source_id', 'depot_code', name='uq_computed_stock_balances_key')
    )
    op.create_index(op.f('ix_computed_stock_balances_article_source_id'), 'computed_stock_balances', ['article_source_id'], unique=False)
    op.create_index(op.f('ix_computed_stock_balances_depot_code'), 'computed_stock_balances', ['depot_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_computed_stock_balances_depot_code'), table_name='computed_stock_balances')
    op.drop_index(op.f('ix_computed_stock_balances_article_source_id'), table_name='computed_stock_balances')
    op.drop_table('computed_stock_balances')
    op.drop_index(op.f('ix_computed_production_status_article_source_id'), table_name='computed_production_status')
    op.drop_table('computed_production_status')
    op.drop_index(op.f('ix_computed_order_lines_order_source_id'), table_name='computed_order_lines')
    op.drop_index(op.f('ix_computed_order_lines_article_source_id'), table_name='computed_order_lines')
    op.drop_table('computed_order_lines')
    # ### end Alembic commands ###
