"""unit_price_value_remaining

Revision ID: d8a9d6cb7458
Revises: efa004ca9777
Create Date: 2026-03-25 13:59:49.063239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a9d6cb7458'
down_revision: Union[str, Sequence[str], None] = 'efa004ca9777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computed_order_lines', sa.Column('unit_price', sa.Numeric(precision=13, scale=4), nullable=True))
    op.add_column('computed_order_lines', sa.Column('value_remaining', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('fact_order_lines', sa.Column('unit_price', sa.Numeric(precision=13, scale=4), nullable=True))
    op.add_column('sync_order_lines', sa.Column('unit_price', sa.Numeric(precision=13, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_order_lines', 'unit_price')
    op.drop_column('fact_order_lines', 'unit_price')
    op.drop_column('computed_order_lines', 'value_remaining')
    op.drop_column('computed_order_lines', 'unit_price')
    # ### end Alembic commands ###
